version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing Maven
      - mvn clean install -DskipTests
artifacts:
  files:
    - 'target/fremontmi-0.0.1-SNAPSHOT.jar
'
